### ISSUE TITLE
Can't start the script: java.lang.ClassNotFoundException: uk.me.mantas.eternity.EternityKeeper

### ISSUE THREAD

**Issue by studiosusmed** [ktully/eternity-keeper#1]
hi,

i have a problem when i trying to execute the script on linux (ubuntu 20.04). Could manage to build the project successfully. 

Received the following message:
```
Symbolic links need to be set up before running this script.
Please run the following (possibly as root).
ln -s "/home/name/Path/eternity-keeper/lib/native/linux64/snapshot_blob.bin" "/usr/lib/jvm/java-15-oracle/bin/snapshot_blob.bin"
ln -s "/home/name/Path/eternity-keeper/lib/native/linux64/natives_blob.bin" "/usr/lib/jvm/java-15-oracle/bin/natives_blob.bin"
ln -s "/home/name/Path/eternity-keeper/lib/native/linux64/icudtl.dat" "/usr/lib/jvm/java-15-oracle/bin/icudtl.dat"
```
which was successful.

When I start the script by ./run.sh I get the following:

```
Error: Could not find or load main class uk.me.mantas.eternity.EternityKeeper
Caused by: java.lang.ClassNotFoundException: uk.me.mantas.eternity.EternityKeeper

```
java -version 

```
java version "15.0.2" 2021-01-19
Java(TM) SE Runtime Environment (build 15.0.2+7-27)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)
```

If I switch my java version to JDK 8 the error persists:

`Error: Could not find or load main class uk.me.mantas.eternity.EternityKeeper`

java -version 

```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```

in the run.sh file the name of the executable jar has to be changed from

`-cp "${cp}target/eternity-0.1.jar" \`
to
`-cp "${cp}target/eternity-0.20a.jar" \ `

**Comment by ktully** [comment]
Can you attach the jar file you built? It doesn't sound like your issue is related to my changes.  

You might have better luck running the pre-built jar from https://github.com/ktully/eternity-keeper/releases/download/0-20.a/Eternity.Keeper.win64-75-0-20a.zip ? It's under  Eternity Keeper win64-75-0-20a\EternityKeeper\jar ; you'll need to move and rename it to match the jar name in your .sh file (I realize that's a Windows release and you're on Linux, but I think the jar should be fine; it's just the native wrapper that's different).

This is my fork of https://bitbucket.org/Fyorl/eternity-keeper/src/master/ with a patch to make Gamepass saves backwards compatible. So unless you need that functionality, you might have more luck with upstream.

Good catch on needing to bump the version number in the scripts (same issue with the .bat); I don't use them so I hadn't noticed that.

**Comment by studiosusmed** [comment]
Thanks ktully for your fast response. Works flawlessly now! Any chance to edit items and skill sets in the near future? all the best!

**Comment by ktully** [comment]
Did the jar from my release work for you? I had a feeling your jar might not have built correctly.

Glad you got it sorted anyway. I'll note your suggestions (I think they were on @Fyorl's wishlist also) but I'm unlikely to get to it anytime soon. I'm sure he'd accept a patch from you though :)

**Comment by studiosusmed** [comment]
believe me I'd like to help. But my coding powers are beyond noob. :) thx anyway!
